#input_path: C:\\Users\\torao\\Pictures\\Pages\\Pages
#input_path : C:\\Users\\torao\\Pictures\\Pages\\Pages_P
input_path: ./data/input
output_path: ./data/output
#reader:
#  mode: word
#  page: double
#  line_ksize: [12, 3]
#  word_ksize: [8, 10]